version: '1.0'
services:
  - name: db
    type: mariadb
    version: 10.4
    configuration: StandAlone
    username: null
    database: null
    userPassword: null
    password: null
    ports:
      - 3306
    remoteAccess: false
    deployTo:
      - mariadb

  - name: pma
    type: docker
    image: phpmyadmin/phpmyadmin
    version: latest
    ports:
      - 80
    remoteAccess: false
    env:
      PMA_HOST: "{{=service('db').getMasterAlias()}}"
      PMA_PORT: "{{=service('db').getMainPort()}}"
    deployTo:
      - mariadb

  - name: web
    type: nginx
    version: 1.17
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: pma
    deployTo:
      - mariadb

hosts:
  - name: mariadb
    requirements:
      cores: 1
      memory: 1
